"""empty message

Revision ID: 889abce0eaa8
Revises: 50c8bd2b789f
Create Date: 2021-02-20 16:44:20.096679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889abce0eaa8'
down_revision = '50c8bd2b789f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    # ### end Alembic commands ###
